(define (problem tufox-instance)
  (:domain tufox)
  (:objects
    detective player bunny1 bunny2 bunny3 bunny4 - agent
    tower library armory observatory
    hall dining_room kitchen storage
    study throne_room bathroom bedroom
    chapel dungeon wine_cellar balcony - room
  )
  (:init
    (alive detective)
    (alive player)
    (alive bunny1)
    (alive bunny2)
    (alive bunny3)
    (alive bunny4)
    (at detective balcony)
    (at player kitchen)
    (at bunny1 library)
    (at bunny2 storage)
    (at bunny3 bedroom)
    (at bunny4 tower)
    (connected tower library)
    (connected library tower)
    (connected library armory)
    (connected armory library)
    (connected armory observatory)
    (connected observatory armory)
    (connected hall dining_room)
    (connected dining_room hall)
    (connected dining_room kitchen)
    (connected kitchen dining_room)
    (connected kitchen storage)
    (connected storage kitchen)
    (connected study throne_room)
    (connected throne_room study)
    (connected throne_room bathroom)
    (connected bathroom throne_room)
    (connected bathroom bedroom)
    (connected bedroom bathroom)
    (connected chapel dungeon)
    (connected dungeon chapel)
    (connected dungeon wine_cellar)
    (connected wine_cellar dungeon)
    (connected wine_cellar balcony)
    (connected balcony wine_cellar)
    (connected tower hall)
    (connected hall tower)
    (connected library dining_room)
    (connected dining_room library)
    (connected armory kitchen)
    (connected kitchen armory)
    (connected observatory storage)
    (connected storage observatory)
    (connected study chapel)
    (connected study hall)
    (connected chapel study)
    (connected hall study)
    (connected throne_room dungeon)
    (connected throne_room dining_room)
    (connected dungeon throne_room)
    (connected dining_room throne_room)
    (connected bathroom wine_cellar)
    (connected bathroom kitchen)
    (connected wine_cellar bathroom)
    (connected kitchen bathroom)
    (connected bedroom balcony)
    (connected bedroom storage)
    (connected balcony bedroom)
    (connected storage bedroom)
    (fox player)
  )
  (:goal (and
    (inspected player)
    (inspected bunny1)
    (inspected bunny2)
    (inspected bunny3)
    (inspected bunny4)
  ))
)
